using System;
using System.Collections.Generic;
using System.Linq;
using nadena.dev.ndmf;
using nadena.dev.ndmf.animator;
using UnityEditor;
using UnityEngine;
using VRC.Dynamics;
using VRC.SDK3.Dynamics.PhysBone.Components;

namespace VRCBoneMerger
{
    /// <summary>
    /// Snapshot of animation bindings relevant to safe PhysBone merging. The editor
    /// scanner reads referenced controllers; the build pass reads NDMF's virtualized
    /// controllers so animations generated by other NDMF plugins are also covered.
    /// </summary>
    internal sealed class VRCBoneMergerAnimationSafety
    {
        private readonly HashSet<VRCPhysBone> animatedPhysBones = new HashSet<VRCPhysBone>();
        private readonly HashSet<GameObject> animatedActiveObjects = new HashSet<GameObject>();

        private VRCBoneMergerAnimationSafety() { }

        internal static VRCBoneMergerAnimationSafety FromAvatar(GameObject avatar)
        {
            var result = new VRCBoneMergerAnimationSafety();
            if (avatar == null) return result;

            var animatedPhysBonePaths = new HashSet<string>(StringComparer.Ordinal);
            var animatedActivePaths = new HashSet<string>(StringComparer.Ordinal);

            foreach (AnimationClip clip in CollectReferencedClips(avatar))
            {
                if (clip == null) continue;
                foreach (EditorCurveBinding binding in AnimationUtility.GetCurveBindings(clip))
                {
                    if (IsPhysBoneBinding(binding.type)) animatedPhysBonePaths.Add(binding.path ?? string.Empty);
                    if (binding.type == typeof(GameObject) && binding.propertyName == "m_IsActive")
                        animatedActivePaths.Add(binding.path ?? string.Empty);
                }
            }

            foreach (VRCPhysBone physBone in avatar.GetComponentsInChildren<VRCPhysBone>(true))
            {
                if (physBone == null) continue;
                if (animatedPhysBonePaths.Contains(Path(avatar.transform, physBone.transform)))
                    result.animatedPhysBones.Add(physBone);
                if (animatedActivePaths.Contains(Path(avatar.transform, physBone.transform)))
                    result.animatedActiveObjects.Add(physBone.gameObject);
                Transform root = EffectiveRoot(physBone);
                if (root != null && animatedActivePaths.Contains(Path(avatar.transform, root)))
                    result.animatedActiveObjects.Add(root.gameObject);
            }

            return result;
        }

        internal static VRCBoneMergerAnimationSafety FromNdmf(BuildContext context,
            IEnumerable<VRCPhysBone> physBones)
        {
            var result = new VRCBoneMergerAnimationSafety();
            AnimatorServicesContext services = context.Extension<AnimatorServicesContext>();
            AnimationIndex animationIndex = services.AnimationIndex;
            ObjectPathRemapper remapper = services.ObjectPathRemapper;

            var objects = new HashSet<GameObject>();
            foreach (VRCPhysBone physBone in physBones.Where(x => x != null))
            {
                string componentPath = remapper.GetVirtualPathForObject(physBone.gameObject);
                if (HasBinding(animationIndex, componentPath, binding => IsPhysBoneBinding(binding.type)))
                    result.animatedPhysBones.Add(physBone);

                objects.Add(physBone.gameObject);
                Transform root = EffectiveRoot(physBone);
                if (root != null) objects.Add(root.gameObject);
            }

            foreach (GameObject gameObject in objects.Where(x => x != null))
            {
                string path = remapper.GetVirtualPathForObject(gameObject);
                if (HasBinding(animationIndex, path,
                        binding => binding.type == typeof(GameObject) && binding.propertyName == "m_IsActive"))
                    result.animatedActiveObjects.Add(gameObject);
            }

            return result;
        }

        internal bool HasAnimatedPhysBone(VRCPhysBone physBone)
        {
            return physBone != null && animatedPhysBones.Contains(physBone);
        }

        internal bool HasAnimatedActiveState(GameObject gameObject)
        {
            return gameObject != null && animatedActiveObjects.Contains(gameObject);
        }

        private static bool HasBinding(AnimationIndex index, string path,
            Func<EditorCurveBinding, bool> predicate)
        {
            return index.GetClipsForObjectPath(path)
                .SelectMany(clip => clip.GetFloatCurveBindings())
                .Any(binding => binding.path == path && predicate(binding));
        }

        private static string Path(Transform avatarRoot, Transform transform)
        {
            if (avatarRoot == null || transform == null) return string.Empty;
            if (transform == avatarRoot) return string.Empty;
            return AnimationUtility.CalculateTransformPath(transform, avatarRoot);
        }

        private static bool IsPhysBoneBinding(Type type)
        {
            return type != null && typeof(VRCPhysBoneBase).IsAssignableFrom(type);
        }

        private static Transform EffectiveRoot(VRCPhysBone component)
        {
            return component.rootTransform != null ? component.rootTransform : component.transform;
        }

        private static IEnumerable<AnimationClip> CollectReferencedClips(GameObject avatar)
        {
            var clips = new HashSet<AnimationClip>();
            var controllers = new HashSet<RuntimeAnimatorController>();

            foreach (Animator animator in avatar.GetComponentsInChildren<Animator>(true))
                if (animator != null && animator.runtimeAnimatorController != null)
                    controllers.Add(animator.runtimeAnimatorController);

            foreach (Animation animation in avatar.GetComponentsInChildren<Animation>(true))
            {
                if (animation == null) continue;
                foreach (AnimationClip clip in AnimationUtility.GetAnimationClips(animation.gameObject))
                    if (clip != null) clips.Add(clip);
            }

            // Avatar descriptors and NDMF authoring components (for example Modular
            // Avatar Merge Animator) keep controllers in serialized object references.
            foreach (Component component in avatar.GetComponentsInChildren<Component>(true))
            {
                if (component == null || component is Transform || component is VRCPhysBone
                    || component is Renderer || component is Collider) continue;
                try
                {
                    SerializedObject serialized = new SerializedObject(component);
                    SerializedProperty iterator = serialized.GetIterator();
                    bool enterChildren = true;
                    while (iterator.Next(enterChildren))
                    {
                        enterChildren = true;
                        if (iterator.propertyType != SerializedPropertyType.ObjectReference) continue;
                        UnityEngine.Object referenced = iterator.objectReferenceValue;
                        RuntimeAnimatorController controller = referenced as RuntimeAnimatorController;
                        if (controller != null) controllers.Add(controller);
                        AnimationClip clip = referenced as AnimationClip;
                        if (clip != null) clips.Add(clip);
                    }
                }
                catch (Exception)
                {
                    // Unsupported custom inspectors do not make the build unsafe: the
                    // NDMF build-time snapshot performs the authoritative re-check.
                }
            }

            foreach (RuntimeAnimatorController controller in controllers)
                foreach (AnimationClip clip in controller.animationClips)
                    if (clip != null) clips.Add(clip);

            return clips;
        }
    }
}
